### ISSUE TITLE
Breaking error:  The method 'hashValues' isn't defined for the class

### ISSUE THREAD

**Issue by mark8044** [aloisdeniel/figma_squircle#17]
It looks like latest `master` branch PR has dropped `hashValues/hashList` support https://github.com/flutter/flutter/pull/151677.  It seems this is somehow causing a breaking change for this repo with the following errors: 

```
../../../.pub-cache/hosted/pub.dev/figma_squircle-0.5.3/lib/src/smooth_radius.dart:159:23: Error: The method 'hashValues' isn't defined for the class 'SmoothRadius'.
 - 'SmoothRadius' is from 'package:figma_squircle/src/smooth_radius.dart' ('../../../.pub-cache/hosted/pub.dev/figma_squircle-0.5.3/lib/src/smooth_radius.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
  int get hashCode => hashValues(cornerRadius, cornerSmoothing);
                      ^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/figma_squircle-0.5.3/lib/src/smooth_rectangle_border.dart:189:23: Error: The method 'hashValues' isn't defined for the class 'SmoothRectangleBorder'.
 - 'SmoothRectangleBorder' is from 'package:figma_squircle/src/smooth_rectangle_border.dart' ('../../../.pub-cache/hosted/pub.dev/figma_squircle-0.5.3/lib/src/smooth_rectangle_border.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
  int get hashCode => hashValues(side, borderRadius, borderAlign);
                      ^^^^^^^^^^
```

This is by far one of the best packages our so I hope this can get fixed, altho I know this repo has not really been updated recently...

**Comment by chahohbily** [comment]
Same here. Any updates?

**Comment by btrautmann** [comment]
Always a good idea to pin to a ref so you don't adopt unexpected changes:

```yaml
figma_squircle: # It was on 0.5.3 before being broken by Flutter 3.27.0. This is a fork that fixes it.
  git:
    url: https://github.com/Ax0elz/figma_squircle
    ref: 5f1ad5aaccdf31fc398fc141979ea845a0f45383 # The ref that fixes the issue
```
